name: "Base Setup"
description: "Set ups the build environment for this repository."

runs:
  using: composite
  steps:
    - name: "Set up JDK 8."
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: zulu

    - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
      uses: actions/checkout@v3
