org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048M -Dorg.gradle.deprecation.trace=true

org.gradle.warning.mode=fail
org.gradle.kotlin.dsl.allWarningsAsErrors=true

org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.parallel=true
# Cannot yet enable because AGP accesses rootProject.
#org.gradle.unsafe.isolated-projects=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache-problems=fail
org.gradle.configuration-cache.quiet=true

android.useAndroidX=true
android.experimental.lint.missingBaselineIsEmptyBaseline=true

# Work around AGP 9.4.1 / UTP failing to resolve additional test output paths on API 21.
android.enableAdditionalTestOutput=false

android.suppressUnsupportedOptionWarnings=\
  android.enableAdditionalTestOutput,\
  android.experimental.lint.missingBaselineIsEmptyBaseline,\
  android.sync.suppressAgpWarnings,\
  android.suppressUnsupportedOptionWarnings

# TODO WARNING: androidTestImplementation dependencies are ignored because androidTest is disabled.
android.sync.suppressAgpWarnings=GENERIC

# TODO disable this and fix all the R classes.
android.nonTransitiveRClass=false

kotlin.stdlib.default.dependency=false

dependency.analysis.compatibility=DEBUG
