[versions]
project = "1.0"
java = "1.8"

agp = "7.4.2"
# https://github.com/TWiStErRob/net.twisterrob.gradle/releases
twisterrob = "0.15"
detekt = "1.22.0"

jsr305 = "3.0.2"
jbrAnn = "18.0.0"
slf4j = "1.7.30"

# https://developer.android.com/jetpack/androidx/releases/annotation
androidx-annotation="1.1.0"
# https://developer.android.com/jetpack/androidx/releases/annotation
# Override for a transitive Material lib dependency to fix a lint issue.
# ObsoleteLintCustomCheck Lint found an issue registry (`androidx.annotation.experimental.lint.ExperimentalIssueRegistry`) which did not specify the Lint API version it was compiled with.
androidx-annotation_experimental="1.1.0-alpha01"
# https://developer.android.com/jetpack/androidx/releases/fragment
androidx-fragment="1.2.5"
# https://developer.android.com/jetpack/androidx/releases/appcompat
androidx-appcompat="1.2.0"
# https://developer.android.com/jetpack/androidx/releases/core
androidx-core="1.3.2"
# https://developer.android.com/jetpack/androidx/releases/multidex
androidx-multidex="2.0.1"
# https://developer.android.com/jetpack/androidx/releases/exifinterface
androidx-exif="1.3.1"
# https://developer.android.com/jetpack/androidx/releases/recyclerview
androidx-recyclerview="1.1.0"
# https://developer.android.com/jetpack/androidx/releases/cardview
androidx-cardview="1.0.0"
# https://developer.android.com/jetpack/androidx/releases/drawerlayout
androidx-drawerlayout="1.1.1"
# https://developer.android.com/jetpack/androidx/releases/swiperefreshlayout
androidx-swiperefreshlayout="1.1.0"
# https://developer.android.com/jetpack/androidx/releases/preference
androidx-preference="1.1.1"
# https://github.com/material-components/material-components-android/releases
androidx-material="1.2.1"

androidx-test-robolectric="4.4"
# https://developer.android.com/jetpack/androidx/releases/test
androidx-test-espresso="3.3.0"
androidx-test-runner="1.3.0"
androidx-test-junit="1.1.2"
androidx-test-uiautomator="2.2.0"

test-junit="4.13.1"
test-params="1.1.1"
test-gwen = "1.0.2"
test-mockito="3.3.3"
test-powermock="2.0.7"
# Use this instead of 1.3
# If `hamcrest-1.3` appears in the dependency list, check if it's excluded from all usages.
test-hamcrest="2.0.0.0"

test-android-dexmaker="1.0"

# TODEL SVGWorkarounds on > 1.4
# TODEL :glide3 consumer.pro on > 1.4
svg = "1.4"
glide3 = "3.8.0"
guava-android = "27.0.1-android"
android-lrucache = "2.0.2"
android-colorpicker = "2.4.2"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
twisterrob-quality = { module = "net.twisterrob.gradle:twister-quality", version.ref = "twisterrob" }
twisterrob-android = { module = "net.twisterrob.gradle:twister-convention-plugins", version.ref = "twisterrob" }

annotations-jetbrains = { module = "org.jetbrains:annotations", version.ref = "jbrAnn" }
annotations-jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

glide3 = { module = "com.github.bumptech.glide:glide", version.ref = "glide3" }
androidSVG = { module = "com.caverock:androidsvg", version.ref = "svg" }
guava-android = { module = "com.google.guava:guava", version.ref = "guava-android" }
android-lrucache = { module = "com.jakewharton:disklrucache", version.ref = "android-lrucache" }
android-colorpicker = { module = "com.rarepebble:colorpicker", version.ref = "android-colorpicker" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-annotation_experimental = { module = "androidx.annotation:annotation-experimental", version.ref = "androidx-annotation_experimental" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidx-fragment" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "androidx-multidex" }
androidx-exif = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exif" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "androidx-drawerlayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-material = { module = "com.google.android.material:material", version.ref = "androidx-material" }

androidx-test-fragment = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-espresso-idle = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "androidx-test-espresso" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-test-espresso" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso" }
androidx-test-espresso-web = { module = "androidx.test.espresso:espresso-web", version.ref = "androidx-test-espresso" }
androidx-test-espresso-accessibility = { module = "androidx.test.espresso:espresso-accessibility", version.ref = "androidx-test-espresso" }
androidx-test-espresso-concurrent = { module = "androidx.test.espresso:espresso-concurrent", version.ref = "androidx-test-espresso" }
androidx-test-espresso-net = { module = "androidx.test.espresso:espresso-net", version.ref = "androidx-test-espresso" }

androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-runner" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-test-uiautomator" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-runner" }
androidx-test-robolectric = { module = "org.robolectric:robolectric", version.ref = "androidx-test-robolectric" }
androidx-test-robolectric-multidex = { module = "org.robolectric:shadows-multidex", version.ref = "androidx-test-robolectric" }

test-junit = { module = "junit:junit", version.ref = "test-junit" }
test-params = { module = "pl.pragmatists:JUnitParams", version.ref = "test-params" }
test-gwen = { module = "com.shazam:gwen", version.ref = "test-gwen" }

test-hamcrest = { module = "org.hamcrest:java-hamcrest", version.ref = "test-hamcrest" }
test-hamcrest-junit = { module = "org.hamcrest:hamcrest-junit", version.ref = "test-hamcrest" }
# Deprecated ones, exist for reference only.
test-hamcrest-core = { module = "org.hamcrest:hamcrest-core" }
test-hamcrest-library = { module = "org.hamcrest:hamcrest-library" }

test-mockito = { module = "org.mockito:mockito-core", version.ref = "test-mockito" }
test-mockito-android = { module = "org.mockito:mockito-android", version.ref = "test-mockito" }

test-powermock-mockito2 = { module = "org.powermock:powermock-api-mockito2", version.ref = "test-powermock" }
test-powermock-junit4 = { module = "org.powermock:powermock-module-junit4", version.ref = "test-powermock" }
test-powermock-junit4Rule = { module = "org.powermock:powermock-module-junit4-rule", version.ref = "test-powermock" }
test-powermock-junit4Agent = { module = "org.powermock:powermock-module-junit4-rule-agent", version.ref = "test-powermock" }
test-powermock-xstream = { module = "org.powermock:powermock-classloading-xstream", version.ref = "test-powermock" }

test-android-dexmaker = { module = "com.google.dexmaker:dexmaker", version.ref = "test-android-dexmaker" }
test-android-dexmaker-mockito = { module = "com.google.dexmaker:dexmaker-mockito", version.ref = "test-android-dexmaker" }

[bundles]
test-powermock = [
    "test-powermock-mockito2",
    "test-powermock-junit4",
    "test-powermock-junit4Rule",
    # Contains duplicate PowerMockRule which messes things up, do not enable.
    #"test-powermock-junit4Agent",
    "test-powermock-xstream",
]


[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
