[versions]
project = "1.0"
java = "1.8"

agp = "7.4.2"
# https://github.com/TWiStErRob/net.twisterrob.gradle/releases
twisterrob = "0.15"
detekt = "1.22.0"

jsr305 = "3.0.2"
slf4j = "1.7.30"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
twisterrob-quality = { module = "net.twisterrob.gradle:twister-quality", version.ref = "twisterrob" }
twisterrob-android = { module = "net.twisterrob.gradle:twister-convention-plugins", version.ref = "twisterrob" }

jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[bundles]

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
