[versions]
agp = "7.4.2"
# https://github.com/TWiStErRob/net.twisterrob.gradle/releases
twisterrob = "0.15"
java = "1.8"
# https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md
kotlin = "1.8.10"
# https://github.com/detekt/detekt/releases
kotlin-detekt = "1.22.0"

[libraries]
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "kotlin-detekt" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
twisterrob-quality = { module = "net.twisterrob.gradle:twister-quality", version.ref = "twisterrob" }
twisterrob-android = { module = "net.twisterrob.gradle:twister-convention-plugins", version.ref = "twisterrob" }

[bundles]

[plugins]
