name: "🔨 Build & Verify"
on:
  workflow_call:

jobs:

  build:
    name: "build"
    timeout-minutes: 30

    permissions:
      # actions/checkout
      contents: read
      # EnricoMi/publish-unit-test-result-action -> https://github.com/EnricoMi/publish-unit-test-result-action#permissions
      checks: write
      # github/codeql-action/upload-sarif -> https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
      security-events: write

    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash

    steps:

      - name: "Set up JDK 17."
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: zulu

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v5

      - name: "Build & Verify."
        run: >
          ./gradlew
          --no-daemon
          --no-configuration-cache
          --no-build-cache
          --stacktrace
          --continue
          build
          buildHealth
          lint
          violationCountFile
          violationReportConsole
          violationReportHtml

      - name: "Upload 'Lint Results HTMLs' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'Lint Results HTMLs'
          if-no-files-found: error
          path: ${{ github.workspace }}/**/build/reports/lint-results*.html

      - name: "Upload 'Lint Merged Results' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'Lint Merged Results'
          if-no-files-found: error
          path: ${{ github.workspace }}/build/reports/violations.*

      - name: "Fail if there are violations."
        if: ${{ success() || failure() }}
        env:
          LINT_XML: twister-lib-android/config/lint/lint.xml
          VIOLATIONS: ${{ github.workspace }}/build/reports/violations.count
        run: |
          count=$(cat "${VIOLATIONS}")
          if [[ "$count" != "0" ]]; then
            echo "::error file=${LINT_XML},title=Android Lint::There were ${count} violations."
            exit 1
          else
            echo "No violations found."
            exit 0
          fi

      - name: "Upload 'Detekt Results' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'Detekt Results'
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/**/build/reports/detekt/detekt.*

      - name: "Publish 'Code scanning results / detekt' GitHub Code Scanning analysis."
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ success() || failure() }}
        with:
          sarif_file: ${{ github.workspace }}/gradle/plugins/build/reports/detekt/detekt.sarif

      - name: "Upload 'Unit Test Results' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'Unit Test Results'
          if-no-files-found: error
          path: ${{ github.workspace }}/**/build/reports/tests/*/

      - name: "Publish 'Unit Results' check suite."
        if: ${{ success() || failure() }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: '🔔 Test: Unit Results'
          comment_mode: off
          report_individual_runs: true
          action_fail_on_inconclusive: true
          test_changes_limit: 0
          files: ${{ github.workspace }}/**/build/test-results/*/TEST-*.xml

      - name: "Upload 'Build Health' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'Build Health'
          if-no-files-found: error
          path: ${{ github.workspace }}/build/reports/dependency-analysis/
